version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: booking-postgres-docker
    environment:
      POSTGRES_DB: booking-db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - booking-net

  redis:
    image: redis:7
    container_name: booking-redis-docker
    ports:
      - "6379:6379"
    networks:
      - booking-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: booking-zookeeper-docker
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - booking-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: booking-kafka-docker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - booking-net

  app:
    build: .
    container_name: event-booking-app
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking-db
      SPRING_DATASOURCE_USERNAME: booking_user
      SPRING_DATASOURCE_PASSWORD: booking_pass

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    ports:
      - "8080:8080"
    networks:
      - booking-net

networks:
  booking-net:

volumes:
  pgdata: