server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/booking-db
#    url: jdbc:postgresql://postgres:5433/booking-db
    username: booking_user
    password: booking_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
#   bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: booking-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Correct property names for delegate deserializers
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        # JSON deserializer configuration
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.booking.eventbookingservice.booking.event.BookingConfirmedEvent

        spring.json.type.mapping: bookingConfirmed:com.booking.eventbookingservice.booking.event.BookingConfirmedEvent

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.kafka: DEBUG  # Add this to see Kafka details

jwt:
  secret: "Jnivjneirnveijvnkeuufn7w4hf8437fnrwen3w4unf848nvsdweunweivbeqifjvnwijrnvi"
  expiration: 7200000